Remove __init__.py from numba/cuda/tests/doc_examples/ffi
It contains no Python code and is causing a traceback with test loading,
reporting:

```
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba_cuda/numba/cuda/tests/__init__.py", line 25, in load_testsuite
    suite.addTests(loader.discover(path))
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmarkall/miniforge3/envs/numbadev/lib/python3.11/unittest/loader.py", line 334, in discover
    tests = list(self._find_tests(start_dir, pattern))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmarkall/numbadev/numba/numba/testing/loader.py", line 15, in _find_tests
    name = self._get_name_from_path(start_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmarkall/miniforge3/envs/numbadev/lib/python3.11/unittest/loader.py", line 356, in _get_name_from_path
    assert not _relpath.startswith('..'), "Path must be within the project"
AssertionError: Path must be within the project
```